### ISSUE TITLE
Feature request: Rename project

### ISSUE THREAD

**Issue by rreuvekamp** [Arceden/ChickenNuggetsGarage#3]
Please rename ChickenNuggetsGarage to VegaKipStuckjesGarage because the current name is offensive to vega(n)'s.

kthxbai

**Comment by twillighagen** [comment]
Nee.

**Comment by rreuvekamp** [comment]
"wontfix" implies you agree that it is a bug. Thanks!

**Comment by twillighagen** [comment]
ok



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Remi Reuvekamp <notifications@github.com>
Datum: 23-01-18 22:56 (GMT+01:00)
Aan: Arceden/ChickenNuggetsGarage <ChickenNuggetsGarage@noreply.github.com>
Cc: "Willighagen TK, Timothy" <t.k.willighagen@st.hanze.nl>, State change <state_change@noreply.github.com>
Onderwerp: Re: [Arceden/ChickenNuggetsGarage] Feature request: Rename project (#3)


"wontfix" implies you agree that it is a bug. Thanks!

**Comment by rreuvekamp** [comment]
Verzonden vanaf Mutt op Parabola GNU/Linux-libre.

**Comment by twillighagen** [comment]
ok



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Remi Reuvekamp <notifications@github.com>
Datum: 23-01-18 22:59 (GMT+01:00)
Aan: Arceden/ChickenNuggetsGarage <ChickenNuggetsGarage@noreply.github.com>
Cc: "Willighagen TK, Timothy" <t.k.willighagen@st.hanze.nl>, State change <state_change@noreply.github.com>
Onderwerp: Re: [Arceden/ChickenNuggetsGarage] Feature request: Rename project (#3)


Verzonden vanaf Mutt op Parabola GNU/Linux-libre.
